# Generated by Django 4.1.2 on 2022-10-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fileshare.patient'),
        ),
    ]
