# Generated by Django 4.1.2 on 2022-10-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0004_alter_file_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.patient'),
        ),
    ]
