# Generated by Django 4.1.2 on 2022-10-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_file_file_alter_file_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='DoctorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.doctor')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.file')),
            ],
        ),
    ]
