# Generated by Django 4.1.2 on 2022-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0008_doctorlicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesharerequest',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='filesharerequest',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FileShare',
        ),
        migrations.DeleteModel(
            name='FileShareRequest',
        ),
    ]
