# Generated by Django 4.1.2 on 2022-11-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0009_remove_filesharerequest_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatient',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FileShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.doctor')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.file')),
            ],
        ),
    ]
