# Generated by Django 4.1.2 on 2022-11-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0011_remove_file_file_file_comments_file_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlicense',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DoctorLicenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.doctor')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileshare.doctorlicense')),
            ],
        ),
    ]
