# Generated by Django 4.1.2 on 2022-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0012_doctorlicense_approved_doctorlicenserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='file',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='file',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='file',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
