# Generated by Django 4.1.2 on 2022-12-02 08:57

from django.db import migrations, models
import django.db.models.deletion
import fileshare.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0015_remove_doctorlicenserequest_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlicense',
            name='license',
            field=models.FileField(upload_to=fileshare.models.license_upload_location),
        ),
        migrations.AlterField(
            model_name='doctorlicenserequest',
            name='license',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='fileshare.doctorlicense'),
        ),
    ]
