# Generated by Django 4.1.2 on 2022-12-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileshare', '0016_alter_doctorlicense_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlicense',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorlicense',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
