# Generated by Django 4.1.2 on 2022-12-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0017_remove_doctorlicense_doctor_doctorlicense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlicense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doctorlicenserequest',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorlicense',
            name='doctor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='fileshare.patient'),
        ),
    ]
