# Generated by Django 4.1.2 on 2022-12-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0018_remove_doctorlicense_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorLicenseRequest',
        ),
    ]
